version: '3.3'
services:
  db:
    image: mysql:8.0.20
    restart: always
    environment:
      MYSQL_DATABASE: 'hw'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3344:3306'
    expose:
      - '3344'
